version: '3'

services: 
  php-fpm:
    build: 
      context: ./php-fpm

  nginx:
    build: 
      context: ./nginx
    volumes: 
      - ../src:/var/www/
      - ./nginx/nginx.config:/etc/nginx/nginx.config
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/config.d/:/etc/nginx/config.d
    depends_on: 
      - php-fpm
    ports: 
      - "80:80"
      - "443:443" #host:container
  
  database:
    build: 
      context: ./database
    environment: 
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=docker
    volumes: 
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
